//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Park
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public int Post { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string Surname { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime Last_entry { get; set; }
        public string Type_of_entry { get; set; }
        public string Photo { get; set; }
    
        public virtual Post_id Post_id { get; set; }
    }
}
